import { Platform } from 'react-native';
import Constants from 'expo-constants';
import {
	API_KEY as ENV_API_KEY,
	AUTH_DOMAIN as ENV_AUTH_DOMAIN,
	PROJECT_ID as ENV_PROJECT_ID,
	STORAGE_BUCKET as ENV_STORAGE_BUCKET,
	MESSAGING_SENDER_ID as ENV_MESSAGING_SENDER_ID,
	APP_ID as ENV_APP_ID,
	MEASUREMENT_ID as ENV_MEASUREMENT_ID,
	GOOGLE_WEB_CLIENT_ID as ENV_GOOGLE_WEB_CLIENT_ID,
	EXPO_CLIENT_ID as ENV_EXPO_CLIENT_ID,
	IOS_CLIENT_ID as ENV_IOS_CLIENT_ID,
	ANDROID_CLIENT_ID as ENV_ANDROID_CLIENT_ID,
	WORD_LADDER_BACKEND as ENV_WORD_LADDER_BACKEND,
	REVENUECAT_IOS_API_KEY as ENV_REVENUECAT_IOS_API_KEY,
	REVENUECAT_ANDROID_API_KEY as ENV_REVENUECAT_ANDROID_API_KEY
} from '@env';

// Get config from expo-constants (works with EAS builds)
const extra = Constants.expoConfig?.extra || {};

// Use localhost in development, Railway in production
const getBackendUrl = () => {
	if (__DEV__) {
		// Development builds use localhost
		return Platform.OS === 'ios' ? 'http://localhost:3000' : 'http://10.0.2.2:3000';
	}
	// Production builds use Cloud Run URL from EAS secrets
	return extra.WORD_LADDER_BACKEND || ENV_WORD_LADDER_BACKEND;
};

export default {
	API_KEY: extra.API_KEY || ENV_API_KEY,
	AUTH_DOMAIN: extra.AUTH_DOMAIN || ENV_AUTH_DOMAIN,
	PROJECT_ID: extra.PROJECT_ID || ENV_PROJECT_ID,
	STORAGE_BUCKET: extra.STORAGE_BUCKET || ENV_STORAGE_BUCKET,
	MESSAGING_SENDER_ID: extra.MESSAGING_SENDER_ID || ENV_MESSAGING_SENDER_ID,
	APP_ID: extra.APP_ID || ENV_APP_ID,
	MEASUREMENT_ID: extra.MEASUREMENT_ID || ENV_MEASUREMENT_ID,
	GOOGLE_WEB_CLIENT_ID: extra.GOOGLE_WEB_CLIENT_ID || ENV_GOOGLE_WEB_CLIENT_ID,
	EXPO_CLIENT_ID: extra.EXPO_CLIENT_ID || ENV_EXPO_CLIENT_ID,
	IOS_CLIENT_ID: extra.IOS_CLIENT_ID || ENV_IOS_CLIENT_ID,
	ANDROID_CLIENT_ID: extra.ANDROID_CLIENT_ID || ENV_ANDROID_CLIENT_ID,
	WORD_LADDER_BACKEND: getBackendUrl(),
	REVENUECAT_IOS_API_KEY: extra.REVENUECAT_IOS_API_KEY || ENV_REVENUECAT_IOS_API_KEY,
	REVENUECAT_ANDROID_API_KEY: extra.REVENUECAT_ANDROID_API_KEY || ENV_REVENUECAT_ANDROID_API_KEY,
};