
import {
	API_KEY,
	AUTH_DOMAIN,
	PROJECT_ID,
	STORAGE_BUCKET,
	MESSAGING_SENDER_ID,
	APP_ID,
	MEASUREMENT_ID,
	GOOGLE_WEB_CLIENT_ID,
	EXPO_CLIENT_ID,
	IOS_CLIENT_ID,
	ANDROID_CLIENT_ID
} from '@env';

export default {
	API_KEY,
	AUTH_DOMAIN,
	PROJECT_ID,
	STORAGE_BUCKET,
	MESSAGING_SENDER_ID,
	APP_ID,
	MEASUREMENT_ID,
	GOOGLE_WEB_CLIENT_ID,
	EXPO_CLIENT_ID,
	IOS_CLIENT_ID,
	ANDROID_CLIENT_ID
};