const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// expo-av's EXAV module fails to build when useFrameworks: "static" is set
// (required for Firebase). CocoaPods only allows one post_install block, so
// we inject the DEFINES_MODULE fix inside the existing one generated by RN.
const withEXAVModularHeaders = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfilePath)) return config;

      let podfile = fs.readFileSync(podfilePath, 'utf8');

      // Guard against double-injection
      if (podfile.includes('# withEXAVModularHeaders')) return config;

      const injection = [
        '    # withEXAVModularHeaders: fix expo-av + useFrameworks:static',
        '    installer.pods_project.targets.each do |target|',
        "      if ['EXAV', 'ExpoModulesCore'].include?(target.name)",
        '        target.build_configurations.each do |cfg|',
        "          cfg.build_settings['DEFINES_MODULE'] = 'YES'",
        '        end',
        '      end',
        '    end',
        '',
      ].join('\n');

      // Insert at the top of the existing post_install block
      podfile = podfile.replace(
        /(post_install do \|installer\|\n)/,
        `$1${injection}`
      );

      fs.writeFileSync(podfilePath, podfile);
      console.log('withEXAVModularHeaders: injected DEFINES_MODULE into existing post_install');

      return config;
    },
  ]);
};

module.exports = withEXAVModularHeaders;

