export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const WORD_LADDER_CHANGE = "WORD_LADDER_CHANGE";
export const LEADERBOARD_CHANGE = "LEADERBOARD_CHANGE";
export const LEADERBOARD_GROUPS_CHANGE = "LEADERBOARD_GROUPS_CHANGE";
export const GROUP_LEADERBOARD_CHANGE = "GROUP_LEADERBOARD_CHANGE";